---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      run: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    run: rabbitmq
spec:
  clusterIP: 10.110.10.4
  ports:
    - port: 5672
      protocol: TCP
  selector:
    run: rabbitmq