---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  selector:
    matchLabels:
      run: discovery-service
  replicas: 1
  template:
    metadata:
      labels:
        run: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: albertocampini/discovery-service
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    run: discovery-service
spec:
  clusterIP: 10.110.10.1
  ports:
    - port: 8761
      protocol: TCP
  selector:
    run: discovery-service