---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
spec:
  selector:
    matchLabels:
      run: user-microservice
  replicas: 1
  template:
    metadata:
      labels:
        run: user-microservice
    spec:
      containers:
        - name: user-microservice
          image: albertocampini/user-microservice
          ports:
            - containerPort: 8763